### PR TITLE
chore(package): update dockerlint to version 0.3.7

### PR DESCRIPTION
**Pull request by lucasdf**

### CODE REVIEW

**Comment by Arcanemagus** [comment]
It looks like there have been several bugfix releases there, I'm assuming that's why you want the minimum version bumped?

Btw, would you like to be added as a maintainer on this package as well?

**Comment by lucasdf** [comment]
I thought that it would be a good practice to keep bumping the minimum version as new versions of `dockerlint` are released. 

`dockerlint` is the actual linter used by this package and it is a bundled dependency. Unless we bump the minimum version in `package.json` and release a new version of `linter-docker`, everyone who already has this package installed will keep using the older version of `dockerlint` unless they reinstall `linter-docker` or if they go to the package's directory and update dependencies. Does that make sense? Or does Atom take care of updating the dependencies by itself? Since it is a bundled dependency and it is not managed by the user in the system-level, it *may* make sense for us to force the update.

I would be happy to maintain this package.

**Comment by Arcanemagus** [comment]
> Or does Atom take care of updating the dependencies by itself?

As you stated, Atom only updates this if (re)installing the package, or if asked to rebuild the package dependencies. That's a manual command that is rarely used though.

> Since it is a bundled linter and it is not managed by the user in the system-level, it may make sense for us to force the update.

Absolutely! About half of the bundled ones actually pin the version explicitly so Greenkeeper sends a new PR for each release so it can be updated right away.

> I would be happy to maintain this package.

@johnwebbcole Any objections to adding @lucasdf to the team on this package?

**Comment by johnwebbcole** [comment]
none... welcome aboard!

**Comment by Arcanemagus** [comment]
Done, feel free to merge whenever you want @lucasdf 😉 🎉

**Comment by lucasdf** [comment]
> About half of the bundled ones actually pin the version explicitly so Greenkeeper sends a new PR for each release so it can be updated right away.

do you mean using `0.3.7` instead of `~0.3.7` ?

**Comment by Arcanemagus** [comment]
Yes, that would be pinning it. Generally when the dependency is bundled with no way to use an external version I'd say it should be pinned so we can be sure users are on the current version, unless the package has no active maintainer to keep it up to date like that.

**Comment by lucasdf** [comment]
Version [v0.3.0](https://github.com/AtomLinter/linter-docker/releases/tag/v0.3.0) has been released :-)

**Pull request merged**
