### PR TITLE
Updating dockerlint dependency to 0.2.2

### PR DESCRIPTION
**Pull request by hairyhenderson**
Updating dockerlint dependency to 0.2.2, and also changing the range from a `~` to a `^` so that bugfix releases like this are installed automatically.

### CODE REVIEW

**Comment by johnwebbcole** [comment]
~0.2.0 should already load 0.2.2 on install.

**Comment by hairyhenderson** [comment]
@johnwebbcole ok, I was mistaken - thought `~` acted differently with `0.x.y` versions (was confusing it with `^`). It turns out dockerlint 0.2.2 just hasn't been pushed to npmjs. Thanks!

**Comment by hairyhenderson** [comment]
@johnwebbcole @Arcanemagus looks like 0.2.2 never got released - but 0.3.1 is out now. Merging #33 will upgrade the dep and add the bugfixex I was looking for.

**Comment by Arcanemagus** [comment]
Published in v0.2.0. 😉

**Pull request closed without merging**
